tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DNA_ETL_DEV_ROLE
      database: DNA_DEV_TEST
      schema: dev
      warehouse: ETL_DEV_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: DNA_ETL_PROD_ROLE
      database: DNA_DEV_TEST
      schema: prod
      warehouse: ETL_PROD_WH